server:
  port: 6600

spring:
  profiles:
    active: dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:test}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}

  thymeleaf:
    encoding: UTF-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8

    serialization:
      indent_output: true

logging:
  level:
    root: INFO

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**Mapper.xml
  type-aliases-package: org.harmony.toddler.mybatis.spring.demo

mybatis:
  groovy:
    roots: ${GROOVY_ROOT:script}
